[CRB-202] Add RegisterDealOrder command
gluwa/Creditcoin-Client pull request #7
Opened 2021-10-07 18:54 UTC by nathanwhit

This PR adds the RegisterDealOrder command described in CRB-202 to the client.

2021-11-15 19:40 UTC, atodorov requested changes
@nathanwhit I think this is good for merge but will need the rebase anyway.

2021-11-17 14:37 UTC, CAGS295 commented on ccclient/Program.cs
> +                Console.WriteLine("creditcoin RegisterDealOrder askAddressId bidAddressId amount interest maturity fee expiration fundraiserSignature fundraiserPublicKey dealOrderId txId");
From the tp parser.
```
                    let blockchain_tx_id =
                        get_string(&map, "p11", "blockchainTxId")?.to_lowercase();
```
```suggestion
                Console.WriteLine("creditcoin RegisterDealOrder askAddressId bidAddressId amount interest maturity fee expiration fundraiserSignature fundraiserPublicKey dealOrderId blockchainTxId");
```

2021-11-17 17:22 UTC, nathanwhit commented
@atodorov Rebased and addressed comments, should be ready to merge now

2021-11-17 18:46 UTC, atodorov approved these changes

2021-11-18 20:13 UTC, CAGS295 approved these changes

2021-11-18 20:15 UTC, merged